version: "3.9"
services:
  openq-api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8090:8090"
    environment:
      WALLET_KEY: "0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82"
      OPENQ_ADDRESS: "0x0165878a594ca255338adfa4d48449f69242eb8f"
      RPC_NODE: https://rinkeby.infura.io/v3/3b83a506f358431399e427135570f8e8
    volumes:
      - /app/node_modules
      - ./:/app
    