version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: alo42/openq:latest
        auth:
          username: alo42
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: docker build -t alo42/openq:latest .
  deploy:
    docker:
      - image: alo42/openq:latest
        auth:
          username: alo42
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: docker build -t alo42/openq:latest .
  test:
    docker:
      - image: alo42/openq:latest
        auth:
          username: alo42
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
