version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      # build the application image
      - run: docker build -t alo42/openq:latest .

      # deploy the image
      - run: docker push alo42/openq:latest
